#!/bin/bash

# the usage of this script
function usage()
{
   echo
   echo "${0##*/} -u <url> -n <name> [-i <image>] [-v <version>] [-w <dir>] [-s <time>] [-e <time>] [-W <width>] [-H <height>] [-c <perc>] [-a] [-S] [-h]"
   echo
   echo "Converts a BigBlueButton presentation into a .mp4 video."
   echo
   echo " -h   this help"
   echo " -u   <url>"
   echo "      the link to the presentation"
   echo " -n   <name>"
   echo "      the name for the generated presentation file (excl ext, no spaces)"
   echo " -i   <image>"
   echo "      the docker image to use, default: $IMAGE"
   echo " -v   <version>"
   echo "      the version of the docker image to use, default: $VERSION"
   echo " -w   <dir>"
   echo "      the dir for temp files and the final video, default: $WORKDIR"
   echo " -s   <time>"
   echo "      the start time"
   echo " -e   <time>"
   echo "      the end time"
   echo " -W   <width>"
   echo "      the width of the presentation, default: $WIDTH"
   echo " -H   <height>"
   echo "      the height of the presentation, default: $HEIGHT"
   echo " -c   <perc>"
   echo "      the percentage of the screen to reserve for the webcam (0-100), default: $WEBCAMPERC"
   echo " -S   stretch the webcam by 33% to correct aspect ratio"
   echo " -a   add annotations like whiteboard and red dot cursor"
   echo
   echo "Some accepted TIME formats:"
   echo "- ss seconds (example: 1500 or 1500.3)"
   echo "- mm:ss minutes and seconds"
   echo "- hh:mm:ss hours minutes and seconds"
   echo "- dd:hh:mm:ss days, hours, minutes and seconds"
   echo
}

URL=""
NAME=""
VERSION="2021-06-10"
WORKDIR="."
IMAGE="fracpete/bbb-render"
START=""
END=""
WIDTH="1920"
HEIGHT="1080"
WEBCAMPERC="20"
STRETCHWEBCAM=""
ANNOTATIONS=""

# interpret parameters
while getopts ":hu:n:i:v:w:s:e:W:H:c:aS" flag
do
   case $flag in
      u) URL=$OPTARG
         ;;
      n) NAME=$OPTARG
         ;;
      i) IMAGE=$OPTARG
         ;;
      v) VERSION=$OPTARG
         ;;
      w) WORKDIR=$OPTARG
         ;;
      s) START="-s$OPTARG"
         ;;
      e) END="-e$OPTARG"
         ;;
      W) WIDTH=$OPTARG
         ;;
      H) HEIGHT=$OPTARG
         ;;
      c) WEBCAMPERC=$OPTARG
         ;;
      a) ANNOTATIONS="-a"
         ;;
      S) STRETCHWEBCAM="-S"
         ;;
      h) usage
         exit 0
         ;;
      *) usage
         echo "Unhandled option: flag=$flag arg=$OPTARG"
         exit 1
         ;;
   esac
done

if [ "$URL" = "" ]
then
  echo
  echo "No presentation URL provided!"
  echo
  usage
  exit 1
fi

if [ "$NAME" = "" ]
then
  echo
  echo "No presentation name provided!"
  echo
  usage
  exit 2
fi

CURRDIR=`pwd`

if [ ! "$WORKDIR" = "." ]
then
  cd "$WORKDIR"
fi

docker run -u $(id -u):$(id -g) \
    -v `pwd`:/workspace \
    -t $IMAGE:$VERSION \
    bbbr_convert -u "$URL" -n "$NAME" $START $END -W $WIDTH -H $HEIGHT -c $WEBCAMPERC $ANNOTATIONS $STRETCHWEBCAM

if [ ! "$WORKDIR" = "." ]
then
  cd "$CURRDIR"
fi

